#ifdef MacroUseShortNames
#undef MacroUseShortNames

#undef Nth
#undef Apply
#undef Id
#undef None
#undef Eq
#undef NotEq
#undef Bool
#undef Switch
#undef MaxArgs
#undef ArgCount
#undef Argmap
#undef Reduce
#undef Concat

#endif

#undef IMacro63to0
#undef IMacro64th
#undef IMacro62ones2zeros
#undef MacroNth
#undef IMacroNth_1
#undef IMacroNth_2
#undef IMacroNth_3
#undef IMacroNth_4
#undef IMacroNth_5
#undef IMacroNth_6
#undef MacroApply
#undef MacroId
#undef MacroNone
#undef IMacroFirst
#undef IMacroSecond
#undef IMacroConcat2
#undef IMacroComma
#undef IMacroIsEmpty
#undef IMacroTrue
#undef IMacroFalse
#undef IMacroIf
#undef IMacroIf_1
#undef IMacroIf_0
#undef IMacroAnd
#undef IMacroAnd_1
#undef IMacroAnd_0
#undef IMacroOr
#undef IMacroOr_1
#undef IMacroOr_0
#undef IMacroNot
#undef IMacroNot_1
#undef IMacroNot_0
#undef MacroEq_
#undef MacroEq_0
#undef MacroEq_1
#undef IMacroEq
#undef IMacroEquatable
#undef MacroEq
#undef MacroNotEq
#undef MacroBool
#undef MacroSwitch
#undef MacroMaxArgs
#undef MacroArgCount
#undef Defer
#undef Defer2
#undef Defer3
#undef IMacroExpand0
#undef IMacroExpand1
#undef IMacroExpand2
#undef IMacroExpand3
#undef IMacroExpand4
#undef IMacroExpand5
#undef IMacroMassExpand
#undef Second
#undef MacroEq_IMacroListTerminator
#undef InternalCheck_InternalListTerminator
#undef IMacroArgmap
#undef IMacroArgmapRef
#undef MacroArgmap
#undef IMacroHasComma
#undef IMacroExtractSep
#undef IMacroInParentheses
#undef IMacroExtractSep_0
#undef IMacroExtractSep_1
#undef IMacroFirstOrComma
#undef IMacroFirstOrComma_0
#undef IMacroFirstOrComma_1
#undef IMacroReduce
#undef IMacroReduceRef
#undef MacroReduce
#undef MacroConcat

// can include this module again now
#undef Macro_h
